---
- name: Setup testClient2
  hosts: testClient2
  become: yes
  tasks:
    - name: Install necessary packages
      yum:
        name:
          - iproute
          - iputils
        state: present

    - name: Configure VLAN for testClient2
      command: ip link add link eth0 name eth0.20 type vlan id 20

    - name: Assign IP address to VLAN
      command: ip addr add 10.10.10.254/24 dev eth0.20

    - name: Bring up VLAN interface
      command: ip link set eth0.20 up